apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources
          - name: dashboards-provisioning
            mountPath: /etc/grafana/provisioning/dashboards
          - name: microfail-dashboard-json
            mountPath: /var/lib/grafana/dashboards/microfail
          - name: todo-dashboard-json
            mountPath: /var/lib/grafana/dashboards/todo
          - name: remediator-dashboard-json
            mountPath: /var/lib/grafana/dashboards/remediator
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: dashboards-provisioning
          configMap:
            name: dashboards-provisioning
        - name: microfail-dashboard-json
          configMap:
            name: microfail-dashboard-json
        - name: todo-dashboard-json
          configMap:
            name: todo-dashboard-json
        - name: remediator-dashboard-json
          configMap:
            name: remediator-dashboard-json
