apiVersion: apps/v1
kind: Deployment
metadata:
  name: microfail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microfail
  template:
    metadata:
      labels:
        app: microfail
    spec:
      containers:
        - name: microfail-container
          image: vladbelo2/microfail-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: microfail-service
spec:
  selector:
    app: microfail
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
