apiVersion: v1
kind: Service
metadata:
  name: microfail-service
  labels:
    app: microfail
spec:
  selector:
    app: microfail
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
