apiVersion: apps/v1
kind: Deployment
metadata:
  name: microfail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microfail
  template:
    metadata:
      labels:
        app: microfail
    spec:
      containers:
        - name: microfail-container
          image: vladbelo2/microfail-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
