apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'microfail-app'
        static_configs:
          - targets: ['microfail-service:8000']

      - job_name: 'todo-app'
        static_configs:
          - targets: ['todo-service:5000']

      - job_name: 'remediator'
        static_configs:
          - targets: ['remediator:8001']

      - job_name: 'devops-utils'
        static_configs:
          - targets: ['devops-utils-service:5050']

      # ✅ Enable K8s pod resource metrics via kubelet
      - job_name: 'kubernetes-pods-metrics'
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']

    rule_files:
      - /etc/prometheus/alerts.yml
