apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: todo
spec:
  selector:
    app: todo
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
